<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <AssemblyName>ScrubJay.Reflection.Sandbox</AssemblyName>
        <RootNamespace>ScrubJay.Reflection.Sandbox</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Reflection"/>
        <Using Include="ScrubJay.Reflection.Extensions"/>
        <Using Include="ScrubJay.Extensions"/>
        <Using Include="ScrubJay.Text"/>
        <Using Include="ScrubJay.Text.Comparison"/>
        <Using Include="ScrubJay.Validation"/>
        
        <Using Include="ScrubJay.Functional.Prelude" Static="true"/>
        <Using Include="ScrubJay.Reflection.Prelude" Static="true"/>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\src\ScrubJay.Reflection.csproj" />
    </ItemGroup>

</Project>
